version: '3.8'

services:
  labpal_main:
    image: lorkorblaq/labpal_main:latest
    ports:
      - "8080:8080"
    networks:
      - labpal_network
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager

  labpal_api:
    image: lorkorblaq/labpal_api:latest
    ports:
      - "3000:3000"
    networks:
      - labpal_network
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager

  labpal_gpt:
    image: lorkorblaq/labpal_gpt:latest
    ports:
      - "3500:3500"
    networks:
      - labpal_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"
      placement:
        constraints:
          - node.role == worker

  labpal_nginx:
    image: lorkorblaq/labpal_nginx:secure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt_data:/etc/letsencrypt
    networks:
      - labpal_network
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager

  labpal_redis:
    image: lorkorblaq/labpal_redis:latest
    ports:
      - "6379:6379"
    networks:
      - labpal_network
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

networks:
  labpal_network:
    driver: overlay

volumes:
  letsencrypt_data:
    external: true
